language: node_js
node_js:
  - "11"
cache:
  yarn: true
  directories:
    - node_modules
script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: ceoalmagro/ceoalmagro.github.io
  target-branch: master
  on:
    branch: master
